{ config, pkgs, ... }: {

  imports = [
    ./waybar
    ./binds.nix
  ];

  wayland.windowManager.hyprland = {
    enable = true;
    package = null;
    portalPackage = null;

    settings = {
   
      # -- Startup Applications --
      # These programs will launch automatically when Hyprland starts
      exec-once = [
        # "swww-daemon"    # Background wallpaper daemon for smooth wallpaper changes
        "waybar"         # Status bar for Wayland
        # "hypridle"       # Idle management daemon (handles screen timeout, etc.)
      ];

      # Pywal colors - these will be generated by pywal
      source = "~/.cache/wal/colors-hyprland.conf";
      
      input = {
        kb_layout = "se";
        kb_variant = "";

        follow_mouse = 1;
        sensitivity = 0;
      };

      # -- Monitor Configuration --
      # Format: monitor=NAME,RESOLUTION@REFRESH,POSITION,SCALE
      # monitor = [
        # "preferred,auto,auto"  # Use preferred resolution, auto position/scale
        # "eDP-1, 1920x1080@60.00300, 0x0, 1"  # Specific laptop display config
      # ];

      # -- Program Variables --
      # Define your preferred applications here
      "$terminal" = "kitty";           # Terminal emulator
      "$menu" = "rofi --show drun";    # Application launcher (shows .desktop files)
      # "$fileManager" = "nautilus";   # File manager

      # Bind variables
      "$mod" = "SUPER";
      "$shiftMod" = "SUPER_SHIFT";

      # -- Window Layout and Spacing --
      general = {
        gaps_in = 5;             # Gap between windows (inner)
        gaps_out = 8;            # Gap between windows and screen edges (outer)
        border_size = 1;         # Window border thickness (0 = no borders)
        layout = "dwindle";      # Layout algorithm (dwindle = automatic tiling)
        allow_tearing = false;   # Disable screen tearing (better for most use cases)
      
        # Add these pywal color lines:
        "col.active_border" = "$color1 $color2 45deg";
        "col.inactive_border" = "$color0";
      };      
      
      # -- Window Appearance --
      decoration = {
        rounding = 5;            # Corner rounding radius for windows
        
        # Window opacity settings
        active_opacity = 0.92;   # Opacity of focused windows (0.0-1.0)
        inactive_opacity = 0.92; # Opacity of unfocused windows
        fullscreen_opacity = 1;  # Opacity of fullscreen windows (fully opaque)

        blur = {
          enabled = false;       # Disable blur effects (better performance)
          size = 3;              # Blur radius (if enabled)
          passes = 1;            # Blur quality passes (if enabled)
        };
      };

      animations = {
        enabled = true;          # Enable window animations
        
        # Custom bezier curve for smooth animations
        bezier = "myBezier, 0.05, 0.9, 0.1, 1.05";
        
        # Animation definitions: name, enabled, speed, curve, [additional options]
        animation = [
          "windows, 1, 7, myBezier"                    # Window open/close animations
          "windowsOut, 1, 7, default, popin 80%"      # Window minimize animations
          "border, 1, 10, default"                     # Border color change animations
          "borderangle, 1, 8, default"                 # Border angle animations
          "fade, 1, 7, default"                        # Fade in/out animations
          "workspaces, 1, 6, default"                  # Workspace switch animations
        ];
      };

      # -- Dwindle Layout Settings --
      # Dwindle is an automatic tiling layout
      dwindle = {
        pseudotile = true;       # Enable pseudotiling (floating-like behavior for some windows)
        preserve_split = true;   # Maintain split ratios when windows are added/removed
      };
      
      # -- Master Layout Settings --
      # Alternative to dwindle (not active with current layout setting)
      # master = {
      #  new_is_master = true;    # New windows become the master window
      # };
      
      # -- Gesture Settings --
      gestures = {
        workspace_swipe = false; # Disable touchpad workspace swiping
      };
      
      # -- Miscellaneous Settings --
      misc = {
        force_default_wallpaper = 0;  # Don't force Hyprland's default wallpaper
        disable_hyprland_logo = true; # Hide Hyprland logo on empty workspaces
      };

    };
  };
}
