{ config, pkgs, ... }:

{
  # Install Thunar and necessary plugins
  home.packages = with pkgs; [
    xfce.thunar
    xfce.thunar-volman
    xfce.tumbler
    papirus-icon-theme
  ];

  # GTK theming using pywal output
  gtk = {
    enable = true;

    theme = {
      name = "wal"; # must match the name generated by Pywal
      package = null; # we don’t need to install it; wal creates it in ~/.themes
    };

    iconTheme = {
      name = "Papirus-Dark";
      package = pkgs.papirus-icon-theme;
    };

  };
}